server:
  port: 2573

spring:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        type: trace
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    url: jdbc:mysql://db4free.net:3306/paddyseedexpert?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: gotham25
    password: Gotham@25
    driverClassName: com.mysql.cj.jdbc.Driver

# log4j:
#   appender:
#     rollingFile: org.apache.log4j.RollingFileAppender
#     rollingFile.File: ${logging.path}/UserProfile.log
#     rollingFile.layout: org.apache.log4j.PatternLayout
#     rollingFile.layout.ConversionPattern: \%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n
#     rollingFile.MaxFileSize: 512MB
#     rollingFile.MaxBackupIndex: 25
#     rollingFile.append: true
#   rootCategory: ALL, rollingFile

logging:
  path: logs
  file: ${logging.path}/UserProfile.log
  file.max-size: 512MB
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    rolling-file-name: ${LOG_FILE}.%d{dd-MM-yyyy}.%i.gz
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace